---
- hosts: rhel01-nostromo.demoredhat.com
  become: true
  gather_facts: false
  tasks:
    - name: Check if httpd is running
      check_mode: true
      ansible.builtin.systemd_service:
        state: started
        name: "{{ linux_service | default("httpd") }}"
      register: service_status

    - name: Check if httpd is running
      ansible.builtin.debug:
        msg: "{{ service_status }}"

    - name: Check if httpd is running
      ansible.builtin.debug:
        msg: "{{ service_status.status.ActiveState if service_status.status.ActiveState is defined else 'ActiveState not found' }}"

    - name: Retrieve last 20 lines of httpd logs
      ansible.builtin.command: journalctl -u httpd.service -n 20
      register: httpd_logs
      ignore_errors: true
      when: service_status.changed

    - name: Store httpd logs as a variable
      ansible.builtin.set_fact:
        httpd_log_output: "{{ httpd_logs.stdout }}"

    - name: Display httpd logs
      ansible.builtin.debug:
        msg: "{{ httpd_log_output }}"

    - name: Set stats for next controller job
      ansible.builtin.set_stats:
        data:
          gpt_prompt: "\n\n### Instructions:\nWe have an issue on our RHEL Linux server with the Apache service. The Apache service will not start. Please help me troubleshoot this issue and get the service back online. Here are recent error logs: {{ httpd_log_output }} \n\n### Response:\n"
          max_tokens: 2000
